Better SPA detection for bookmarklet (#28)
* Improved SPA (Single Page Application) detection for bookmarklet. Related prop: `detectSPArouting`
* `detectSPArouting` default prop changed to `false`. 
* Fixed an issue regarding fake heading detection. `Uncaught (in promise) TypeError: e.firstChild.insertAdjacentHTML is not a function.`